### ISSUE TITLE
[Bug]  Amass task fails

### ISSUE THREAD

**Issue by fyoorer** [c0rvax/project-black#65]
**Describe the bug**
Amass task does not work. Task fails as soon as it is started. I tried to find the root cause but could not spot it

This is the stack trace from log file
```
2019-06-03 23:39:19,895 1 ERROR [apscheduler.executors.default:run_coroutine_job:35] Job "Handlers.sender_loop (trigger: interval[0:00:01], next run at: 2019-06-03 23:39:20 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/apscheduler/executors/base_py3.py", line 29, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/app/events_handling/__init__.py", line 46, in sender_loop
    await self.notifier.notify(task_data)
  File "/app/events_handling/new_data_notifier.py", line 23, in notify
    await self.notify_on_scope(project_uuid, text, target, task_status)
  File "/app/events_handling/new_data_notifier.py", line 113, in notify_on_scope
    text = json.loads(text)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
```

**Comment by c0rvax** [comment]
I think your pull-request should solve the described problem. I will go ahead and try to rebuild the container and see if that would fail. If it persists for you, please feel free to reopen this ticket or create a new one. Thanks

https://github.com/c0rvax/project-black/pull/66
